# Generated by Django 3.2.5 on 2022-02-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('scene', models.CharField(blank=True, max_length=500, null=True)),
                ('character', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=1000)),
                ('season', models.CharField(max_length=100)),
                ('episode', models.CharField(max_length=100)),
                ('relevancy', models.IntegerField()),
                ('level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=300)),
            ],
        ),
    ]
