# Generated by Django 3.2.5 on 2022-02-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='level',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='scene',
        ),
    ]
